# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  PROJECT_PATH: Deployment Settings FIle/Deployment Settings File.csproj
  ZIP_PATH: Deployment Settings FIle/bin/Release/net6.0s/publish/Deployment Settings File-Portable.zip
  EXE_PATH: Deployment Settings FIle/bin/Release/net6.0/publish/Deployment Settings File.exe

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal 
    - name: Publish
      run : dotnet publish -c Release --self-contained -p:PublishSingleFile=true
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'dsfg.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        path: ${{ env.EXE_PATH }}
        directory: ${{ env.ZIP_PATH }}
    - name: Create Release    
      uses: ncipollo/release-action@v1.12.0
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.ZIP_PATH }}
          artifactContentType: zip 
          tag: v0.0.${{ github.run_number }}
